POST  http://localhost:3000/departments
content-type: application/json

{
    "code": "PD",
    "name": "Pediatric Dentistry"
}

###
POST  http://localhost:5050/departments
content-type: application/json

{
    "code": "RD",
    "name": "Restorative Dentistry"
}

###
POST  http://localhost:5050/departments
content-type: application/json

{
    "code": "SU",
    "name": "Surgery"
}

###
POST  http://localhost:3000/departments
content-type: application/json

{
    "code": "OR",
    "name": "Orthodontics"
}

### 
GET  http://localhost:3000/departments

### 
GET  http://localhost:5050/departments/6508c6589c43a8f7a5b26908

###
PUT  http://localhost:5050/departments/650ba5b756950fdb7b037054
Content-Type: application/json

{
    "code": "DS",
    "name": "Dental Surgery"
}

###
DELETE  http://localhost:3000/departments/6508c7329c43a8f7a5b26917

###
POST http://localhost:3000/departments/6508c6589c43a8f7a5b26908/employees
content-type: application/json

{
    "name": { "first": "Alfred", "last": "Christensen" },
    "email": "alfredchrist@apollonia.org",
    "phone": "645 565 6568"
}


###
POST http://localhost:3000/departments/6508c6589c43a8f7a5b26908/employees
content-type: application/json

{
    "name": { "first": "John", "last": "Dudley" },
    "email": "johndudley@apollonia.org",
    "phone": "612 865 6558"
}

###
GET http://localhost:5050/departments/6508c6589c43a8f7a5b26908/employees

###
PUT http://localhost:5050/departments/6508c6589c43a8f7a5b26908/employees/650ba5b756950fdb7b037054
Content-Type: application/json


    {
    "name": { "first": "John", "last": "Dudley" },
    "email": "johndudley@apollonia.org",
    "phone": "612 865 6558"
}

###
DELETE  http://localhost:3000/departments/6508c6589c43a8f7a5b26908/employees/65090bb3162e6d066de75b54